### ISSUE TITLE
String commands ends the program 

### ISSUE THREAD

**Issue by JonathanSCE** [deckerego/Macropad_Hotkeys#1]
When having any text in quotes for key presses, the program quits and shows "Code Done Running"  This also causes any modifier keys used to be held down until you reset the MacroPad.  Keycode commands works but there is no way to send a string of text.

**Comment by deckerego** [comment]
Resolved with latest commit to master - @JonathanSCE try again with latest `code.py` and it should work.

**Comment by JonathanSCE** [comment]
It works now, thanks.
