### ISSUE TITLE
lib does not have .mpy files

### ISSUE THREAD

**Issue by mistahBen** [deckerego/Macropad_Hotkeys#7]
Hi there,

I just downloaded your Hotkeys and realized that the lib directory doesn't actually have the `.mpy` files referred to in the readme. Wasn't sure if that was an oversight, I was also able to resolve it using the methods you described (i.e. pulling them from another source) but from the text of the /lib readme it sounds like they should also be there so it runs "out of the box".

**Comment by deckerego** [comment]
The `lib/` directory does have the library files within the _release .zip file_, but the libraries are not committed as part of the git tree. Double-check that they are extracted with [Macropad.Hotkeys.v1.3.zip](https://github.com/deckerego/Macropad_Hotkeys/releases/download/1.3.0/Macropad.Hotkeys.v1.3.zip) - you should see it within that release file. If you don't let me know!

**Comment by deckerego** [comment]
Closing for now - @mistahBen if the above pointer doesn't fix things, let me know and I'll re-open this issue.
